version: '3.1'

services:

    mongo:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: mongodb
        restart: always
        environment:
            MONGO_INITDB_USERNAME: admin
            MONGO_INITDB_PASSWORD: admin
            MONGO_INITDB_DATABASE: mydb
        ports: 
            - 8081:27017
        volumes:
            - ./mongo/:/etc/mongo

volumes:
    mongo: {}